spring.application.name: api-gateway

server.port: 8081
eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka

jwt.secretKey: ${JWT_SECRET_KEY}

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2


        - id: posts-service
          uri: ${POSTS_SERVICE_URI:lb://POSTS-SERVICE}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connection-service
          uri: ${CONNECTION_SERVICE_URI:lb://CONNECTION-SERVICE}
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI:lb://NOTIFICATION-SERVICE}
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: uploader-service
          uri: ${IMAGE_UPLOAD_SERVICE_URI:lb://UPLOADER-SERVICE}
          predicates:
            - Path=/api/v1/uploads/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


      globalcors:
        corsConfigurations:
          '[/**]': # Apply to all endpoints
            allowedOrigins:
              - "http://localhost:5173"
              - "http://192.168.1.6:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true