spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # Apply to all endpoints
            allowedOrigins:
              - "http://localhost:5173"  # Frontend URL
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
