apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: pisal23/linkedin-app-api-gateway
        resources:
          limits:
              memory: "500Mi"
              cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: JWT_SECRET_KEY
          valueFrom:
              secretKeyRef:
                name: my-secret
                key: JWT_SECRET_KEY
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 300
          periodSeconds: 20
          timeoutSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8081

