apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  JWT_SECRET_KEY: YXNkZmxhZGY5OGE3ZGY4OWF5c2Y4ZDl5YXNpdWRmaGE5czg3ZGZhODlzeXVkaGZhOThzZGZ5YWlzdWhkZmE5OHNmeQ==
  CONNECTION_DB_URI: bmVvNGo=
  CONNECTION_DB_USERNAME: bmVvNGo=
  CONNECTION_DB_PASSWORD: cGFzc3dvcmQ=
  NEO4J_AUTH: bmVvNGovcGFzc3dvcmQ=
  NOTIFICATION_DB_URI: bm90aWZpY2F0aW9uLWRi
  NOTIFICATION_DB_NAME: bm90aWZpY2F0aW9uREI=
  NOTIFICATION_DB_USERNAME: cG9zdGdyZXM=
  NOTIFICATION_DB_PASSWORD: cm9vdDEyMw==
  POSTS_DB_URI: cG9zdHMtZGI=
  POSTS_DB_NAME: cG9zdERC
  POSTS_DB_USERNAME: cG9zdGdyZXM=
  POSTS_DB_PASSWORD: cm9vdDEyMw==
  CLOUDINARY_CLOUD_NAME: ZGk4bW5vbWg1
  CLOUDINARY_API_KEY: MzIyOTU3NTg4MzEzNjU4
  CLOUDINARY_API_SECRET: T0lkWWFxNFhKYTFFalQ0dWsxSWNrZ1hHY05V
  GCS_BUCKET_NAME: Y3MtYm9uZGlmeS1wcm9kCg==
  # GCS_ACCESS_CONFIG: s
  USERS_DB_URI: dXNlci1kYg==
  USERS_DB_NAME: dXNlcnNEQg==
  USERS_DB_USERNAME: cG9zdGdyZXM=
  USERS_DB_PASSWORD: cm9vdDEyMw==
 




