apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: pisal23/linkedin-app-notification-service
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_HOST_URL
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: NOTIFICATION_DB_URI
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: NOTIFICATION_DB_NAME
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: NOTIFICATION_DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: NOTIFICATION_DB_PASSWORD
        ports:
        - containerPort: 9040

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 9040

  
