apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pisal23/linkedin-app-user-service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_SERVICE
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: USERS_DB_URI
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: USERS_DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: USERS_DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: USERS_DB_PASSWORD
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: JWT_SECRET_KEY
        ports:
        - containerPort: 9020

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 9020
  