spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

gcs:
  bucket-name: ${GCS_BUCKET_NAME}

  access-account: ${ACCESS_CONFIG}
