spring:
  web:
    mvc:
      cors:
        mappings:
          /api/v1/users/**:
            allowedOrigins: "${FRONTEND_CORS_ORIGIN:http://localhost:5173}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
